### ISSUE TITLE
how can I maintain alignment between your input text and output text?

### ISSUE THREAD

**Issue by onceGot** [yuanxiaosc/BERT-for-Sequence-Labeling-and-Text-Classification#18]
due to WordPiece tokenizer we must take special care for the correct alignment of token to tag. for example, the word "playing" may be split into "play" and "ing", in which case the input token is more than the output label and make it hard in sequence tagging tasks.

**Comment by yuanxiaosc** [comment]
@onceGot 
The use of the WordPiece tokenizer does increase the data preprocessing and the workload on the model output, but it will not have any impact on model training. For example, "playing" is split into "play" and "## ing", then you only need to split the tags corresponding to the original "playing" into two. These two tags correspond to "play" and "# #ing ". Similarly, if the model predicts that the labels corresponding to "play" and "## ing" are output, then these two labels should be combined to correspond to the original "playing".
