### ISSUE TITLE
What's your develop environment?

### ISSUE THREAD

**Issue by jimmy-walker** [yuanxiaosc/BERT-for-Sequence-Labeling-and-Text-Classification#3]
Thanks for sharing the project. I have meet a problem when running script.
I run the script below:
```linux
python run_sequence_labeling.py \ --task_name="atis" \ --do_train=True \ --do_eval=True \ --do_predict=True \ --data_dir=data/atis_Intent_Detection_and_Slot_Filling \ --vocab_file=pretrained_model/uncased_L-12_H-768_A-12/vocab.txt \ --bert_config_file=pretrained_model/uncased_L-12_H-768_A-12/bert_config.json \ --init_checkpoint=pretrained_model/uncased_L-12_H-768_A-12/bert_model.ckpt \ --max_seq_length=128 \ --train_batch_size=32 \ --learning_rate=2e-5 \ --num_train_epochs=1.0 \ --output_dir=./output/atis_Slot_Filling_epoch1/
```
It raise the error as followed. I read the source code from tensorflow, and find the error comes from eval_metrics parameter of tf.contrib.tpu.TPUEstimatorSpec.
```linux
INFO:tensorflow:Error recorded from evaluation_loop: Values of eval_metric_ops m
ust be (metric_value, update_op) tuples, given: Tensor("loss/Neg:0", shape=(?, 1
28), dtype=float32) for key: eval_loss
```
But I don't think it will produce problem. I guess maybe it was related to the develop environment.
My environment is tensorflow=1.11.0, and install tf_metrics from `pip install git+https://github.com/guillaumegenthial/tf_metrics.git` 
I wonder how's your develop environment.
Appreciate for your response.

**Comment by yuanxiaosc** [comment]
@jimmy-walker My development environment is python = 3.6 and tensorflow = 1.12.0.  I'm sorry, because of my personal negligence, I didn't update the code in run_sequence_labeling.py, and now it's fixed.
