### ISSUE TITLE
intent (text) classification not learning at all on custom data

### ISSUE THREAD

**Issue by riturajkunwar** [yuanxiaosc/BERT-for-Sequence-Labeling-and-Text-Classification#5]
accuracy is almost 0. I did create seq.in and label file. its not learning at all.
what possibly am I doing wrong ?

**seq.in (examples):**
      academic writing help
      i need help with academic style writing
      academic style
**label (examples):**
      writing_help
      writing_help
      writing_help
**seq.out (examples):**
      b_writing_help_type o o
      o o o o b_writing_help_type o o
      b_writing_help_type o

I haven't used any tokenization methods, could that be an issue?

when I run the joint training ... intent classification accuracy is 0 but sequence tagging f1 score is around 99%...... what could be possible going wrong with intent classification in both cases on custom data... ?

**Comment by yuanxiaosc** [comment]
@riturajkunwar Not using the tokenization method will not affect the classification effect too much. Based on the current results, I recommend that you perform the classification experiment run_text_classification.py separately and see the results. If you have any questions, please continue to communicate.

**Comment by riturajkunwar** [comment]
Thanks a lot for responding...
It was a silly problem. 
I increased my epochs, reduced my batch size and sequence length. And classification (independently ) is performing well now. 

My number of classes is large I. E. 240 and the dataset size is relatively small I. E. 4k, that's why it is taking more time to converge....

I shall try the joint model next... Hopefully that will work too for me. :)

**Comment by riturajkunwar** [comment]
Thanks Yuan for the code.... joint modelling works fine for me.
I am closing the issue !!!
