### ISSUE TITLE
running with some error

### ISSUE THREAD

**Issue by mzha108** [yuanxiaosc/BERT-for-Sequence-Labeling-and-Text-Classification#7]
W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at save_restore_v2_ops.cc:109 : Not found: Failed to create a NewWriteableFile: ./output_model/snips_join_task_epoch3/model.ckpt-0_temp_7e0392693a3546f29d070ae01f21bbf9/part-00000-of-00001.data-00000-of-00001.tempstate3315450054524548734 : 系统找
不到指定的路径。
; No such process
Segmentation fault

**Comment by yuanxiaosc** [comment]
你把运行的参数发给我看一下，你如果按照README.md中的默认参数是没问题的。

**Comment by mzha108** [comment]
多谢多谢, 我把readme的 output目录换一个就好了...^_^!
兄弟 方便加个联系方式吗??

**Comment by yuanxiaosc** [comment]
欢迎随时与我联系wangzichaochaochao@gmail.com

**Comment by sajastu** [comment]
Just in case for those who run into the same issue. I just removed any checkpoint file from the `output_directory`. Meaning that it should not contain any checkpoint before training. Thereafter, it should start training w/o any error!

**Comment by yuanxiaosc** [comment]
> Just in case for those who run into the same issue. I just removed any checkpoint file from the `output_directory`. Meaning that it should not contain any checkpoint before training. Thereafter, it should start training w/o any error!

Simply change the output directory of the readme.
